name: tattoo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.10+11

environment:
  sdk: '>=2.18.2 <3.0.0'

# flutter pub outdated
# flutter pub upgrade
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # responsive
  device_preview: ^1.1.0
  sizer: ^2.0.15
  responsive_framework: ^0.2.0

  # firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.4.1

  easy_localization: ^3.0.1
  http: ^0.13.4
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  animations: ^2.0.3
  auto_size_text: ^3.0.0
  json_annotation: ^4.6.0
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.7
  flutter_keyboard_visibility: ^5.3.0
  flare_flutter: ^3.0.2
  centered_singlechildscrollview: ^0.1.8
  connectivity_plus: ^3.0.2
  meta: ^1.8.0
  image_picker: ^0.8.6
  extended_image: ^6.3.2
  hexcolor: ^3.0.1
  image_cropper: ^3.0.1
  in_app_purchase: ^3.0.8
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  flutter_downloader: ^1.9.1
  permission_handler: ^10.2.0
  flutter_email_sender: ^5.2.0
  store_redirect: ^2.0.1
  ntp: ^2.0.0
  app_review: ^2.1.2+1
  google_fonts: ^3.0.1
  webview_flutter: ^4.0.2
  upgrader:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
