name: tattoo
description: A new Flutter project.

publish_to: 'none'
version: 1.1.2+20

environment:
  sdk: '>=3.0.5 <4.0.0'

scripts: derry.yaml

# flutter pub outdated
# flutter pub upgrade
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  derry: ^1.5.0

  # responsive
  device_preview: ^1.1.0
  sizer: ^2.0.15
  responsive_framework: ^0.2.0

  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.6

  easy_localization: ^3.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  shared_preferences: ^2.0.15
  logger: ^2.0.1
  cached_network_image: ^3.2.3
  animations: ^2.0.3
  auto_size_text: ^3.0.0
  json_annotation: ^4.6.0
  font_awesome_flutter: ^10.1.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.2
  flutter_keyboard_visibility: ^5.3.0
  flare_flutter: ^3.0.2
  centered_singlechildscrollview: ^0.2.0
  connectivity_plus: ^4.0.2
  meta: ^1.8.0
  image_picker: ^1.0.2
  gallery_saver:
    git:
      url: https://github.com/ersin-kose/gallery_saver.git
      ref: master
  extended_image: ^8.1.0
  hexcolor: ^3.0.1
  image_cropper: ^5.0.0
  in_app_purchase: ^3.1.8
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  flutter_downloader: ^1.11.1
  permission_handler: ^10.2.0
  flutter_email_sender: ^5.2.0
  store_redirect: ^2.0.1
  ntp: ^2.0.0
  app_review:
    git:
      url: https://github.com/ersin-kose/app_review.git
      ref: master
  google_fonts: ^5.1.0
  webview_flutter: ^4.2.2
  upgrader: 8.1.0
  package_info_plus: ^4.1.0
  flutter_local_notifications: ^15.1.0+1
  photo_manager: ^2.7.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
    - family: Neue-Haas-Display
      fonts:
        - asset: assets/fonts/Neue-Haas-Display-Medium.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
